### ISSUE TITLE
@ sign revisions

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#11]
![screenshot from 2015-03-23 18 54 58](https://cloud.githubusercontent.com/assets/6846609/6780830/7ef891ba-d18e-11e4-82b2-aea4d4a77b5c.png)
- [ ] too wide
- [ ] outer stroke weight is not right

**Comment by kosalaya** [comment]
fixed
![default](https://cloud.githubusercontent.com/assets/8073976/6980430/2184a63e-da0f-11e4-8a99-fcaf3de4ef64.jpg)

**Comment by davelab6** [comment]
(image wasn't uploaded before you hit close :)

**Comment by kosalaya** [comment]
fixed that as well :)
