### ISSUE TITLE
Review sinI (ඉ)

### ISSUE THREAD

**Issue by kosalaya** [mooniak/stick-no-bills-font#113]
<img width="244" alt="screen shot 2017-01-31 at 5 08 18 pm" src="https://cloud.githubusercontent.com/assets/8073976/22463516/f15ba18c-e7d7-11e6-9d7f-3ac23aa273b8.png">

**Comment by pathumego** [comment]
8f6aa9410181e8f9d39ef05adebe0a8e26389db1
