### ISSUE TITLE
Review sinSha

### ISSUE THREAD

**Issue by kosalaya** [mooniak/stick-no-bills-font#114]
<img width="442" alt="screen shot 2017-02-15 at 10 43 20 pm" src="https://cloud.githubusercontent.com/assets/8073976/22986049/562a285a-f3d0-11e6-9778-7aa4361c276d.png">
<img width="454" alt="screen shot 2017-02-15 at 10 44 02 pm" src="https://cloud.githubusercontent.com/assets/8073976/22986048/5626a162-f3d0-11e6-992c-645582358c2b.png">

**Comment by pathumego** [comment]
8f6aa9410181e8f9d39ef05adebe0a8e26389db1
