### ISSUE TITLE
review repackaging at tamil-font

### ISSUE THREAD

**Issue by arcturusannamalai** [mooniak/stick-no-bills-font#115]
Dear @mooniak,
Thank you for the nice font and shared under OFL - both Post-no-bills and Yaldevi.

We are repackaging the font at  https://github.com/thamizha/tamil-fonts/tree/master/open-sourced
Please advise if this is sutiable.

Thanks,
-Muthu

**Comment by pathumego** [comment]
@arcturusannamalai Thanks for the notice. Not sure what you are using these for. But if you could help us to make this into a `.deb` would be really nice :) And We release updates here and there, so I suggest implementing  some way of pulling those updates.
