### ISSUE TITLE
Problems in certain kerning classes 

### ISSUE THREAD

**Issue by kosalaya** [mooniak/stick-no-bills-font#16]
Some changes made in certain kerning classes don't work in final otf file. when typed in metric window everything works perfectly.
![kerning probs](https://cloud.githubusercontent.com/assets/8073976/6994029/5b61a42e-db27-11e4-86cd-8e6074b22176.jpg)

**Comment by pathumego** [comment]
@kosalaya On Indesign and testing page too?

**Comment by kosalaya** [comment]
Yep both in testing page and Indesign

**Comment by pathumego** [comment]
I made a video to better explain the problem http://youtu.be/BprzySiCAQU

**Comment by pathumego** [comment]
There's a bunch of duplicate glyphs on the font and this might be the problem.

`/period /quotedbl /plus /asterisk /comma /hyphen /slash /three /zero /quotesingle /ampersand /dollar /parenleft /parenright /exclam`

![screenshot from 2015-04-06 03 34 52](https://cloud.githubusercontent.com/assets/6846609/6998893/fa6b78ba-dc0d-11e4-93ae-5e424949d276.png)

**Comment by pathumego** [comment]
Removing these did not fix the issue

**Comment by davelab6** [comment]
You have a bunch of kerning lookups, which can be compacted into a single one:

![screen shot 2015-04-13 at 4 23 34 pm](https://cloud.githubusercontent.com/assets/261579/7124768/ae9e68ce-e1f9-11e4-95ba-84bc57f6286a.png)

**Comment by pathumego** [comment]
@kosalaya Please look into this ASAP

**Comment by pathumego** [comment]
I cleaned up the files and tested with new combined lookups :) Works
