### ISSUE TITLE
jjj and gj OTF substitutions 

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#20]
![screen shot 2015-04-22 at 11 21 27 pm](https://cloud.githubusercontent.com/assets/6846609/7281302/611e3e0e-e946-11e4-8f2f-d9a281613e1c.png)

**Comment by paarandika** [comment]
What is this?

**Comment by pathumego** [comment]
Ill detail this later, thats why its pushed to a next release
