### ISSUE TITLE
Ya Review

### ISSUE THREAD

**Issue by kosalaya** [mooniak/stick-no-bills-font#24]
@pathumego @DenzelRajitha these are the current options for the letter Ya. which one's better?
![ya option 1](https://cloud.githubusercontent.com/assets/8073976/7833982/deb46d72-0488-11e5-9760-06e7dbe4209b.jpg)
![ya option 2](https://cloud.githubusercontent.com/assets/8073976/7833986/e166a238-0488-11e5-8ab1-3696b2bd6efe.jpg)

**Comment by pathumego** [comment]
Lets do `Da` as well and see. Right now the to otions seems better to me. Next time ost images with all final glyhs :)

**Comment by pathumego** [comment]
@kosalaya Please close this if you are good with this
