### ISSUE TITLE
need review

### ISSUE THREAD

**Issue by kosalaya** [mooniak/stick-no-bills-font#25]
@pathumego @DenzelRajitha  
![image 13](https://cloud.githubusercontent.com/assets/8073976/7854521/d1faee80-0537-11e5-8cc5-8fd4da54eae8.jpg)
![image 14](https://cloud.githubusercontent.com/assets/8073976/7856287/a0d9fc8e-0545-11e5-917d-53f3fe5210d3.jpg)

this is the stage where am at. a brief review is required before further development

**Comment by pathumego** [comment]
I think we solved this last review
