### ISSUE TITLE
develoment of /si_Ba glyph

### ISSUE THREAD

**Issue by kosalaya** [mooniak/stick-no-bills-font#26]
@pathumego what appears to be the best option here? I'd go with the first one. saves a lot of space horizontally.
![ba](https://cloud.githubusercontent.com/assets/8073976/8116713/49a8eeae-10a1-11e5-91c0-aa8fb2672a9e.jpg)

**Comment by pathumego** [comment]
@kosalaya first option is better in many ways. But try to increase the lower terminal space

**Comment by pathumego** [comment]
Discussed!
