### ISSUE TITLE
Spacing Fixes

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#32]
Machan @lazpremarathna please take a close look at spacing. dont leave anything for kerning :)

<img width="328" alt="screen shot 2015-07-22 at 7 39 32 pm" src="https://cloud.githubusercontent.com/assets/6846609/8848819/22b56c64-3158-11e5-9eb2-98c00b06da3a.png">
<img width="350" alt="screen shot 2015-07-22 at 7 39 25 pm" src="https://cloud.githubusercontent.com/assets/6846609/8848820/22b935b0-3158-11e5-9260-57267ccf6920.png">
<img width="268" alt="screen shot 2015-07-22 at 7 39 20 pm" src="https://cloud.githubusercontent.com/assets/6846609/8848821/22ba33a2-3158-11e5-893e-f728eae91fe9.png">
<img width="345" alt="screen shot 2015-07-22 at 7 39 15 pm" src="https://cloud.githubusercontent.com/assets/6846609/8848822/22ba7a42-3158-11e5-97cf-d6a6e31bbb26.png">

**Comment by pathumego** [comment]
Fullstop and generally all the punctuations need more fixes.
<img width="132" alt="screen shot 2015-10-13 at 3 10 18 pm" src="https://cloud.githubusercontent.com/assets/6846609/10457092/9b7a0d18-71bc-11e5-9d89-9e5717fcfa74.png">

**Comment by kosalaya** [comment]
@pathumego seems like some kerning settings are not working. any suggetion? 
<img width="176" alt="screen shot 2015-10-28 at 11 50 11 pm" src="https://cloud.githubusercontent.com/assets/8073976/10798884/c6a91c94-7dcf-11e5-8cee-14d8c724bc1b.png">

**Comment by pathumego** [comment]
ok tray to manage with spacing, dont go into kern with FF. FOr final release, im thinking that we could work with TruFont

**Comment by pathumego** [comment]
@paarandika should enable appending ken data into the build
