### ISSUE TITLE
Weight problem in lowercase

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#4]
Lowe case weight seems low on this image.
 @kosalaya 
![screenshot from 2015-03-04 12 13 03](https://cloud.githubusercontent.com/assets/6846609/6479213/e10180b4-c267-11e4-97bc-8713b7554be1.png)

**Comment by megbaber** [comment]
Hi Pathum!

How do I actually install the new upper case as a ttf on my mac? Meg

**Comment by pathumego** [comment]
Hi double click the file is sent you. when it is opened in the FontBook software, you just click install and it will install.

What I have sent you is an otf file, but it should work fine.
