### ISSUE TITLE
Features for Latin

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#45]
@paarandika  Latin3 requiers some basic features for numerators, fractions and some other basic rendering. Please look into it. Glyphs are already done.

**Comment by pathumego** [comment]
@paarandika  Ping look at Abhaya Latin features for this

**Comment by paarandika** [comment]
I will uncomment the numeral features and see

**Comment by pathumego** [comment]
@paarandika PING

**Comment by paarandika** [comment]
All the Abhaya features are eneables in SNB
