### ISSUE TITLE
Feedback from @davelab6

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#5]
- [x]  Your baseline and overshoot need review. R and Q had uneven baselines by 1 or 2 points. 
- [x]  " needs more white space between the marks; the unit distance if 53 and the distance of the white stripes in your caps is 54... but to me it feels like 50, because there is so much white space in this glyph; so you could set it to just 26 units for each side bearing and the gap to 54. However the quotes look very heavy with lower case. 
- [ ]  $ is nasty. All that black! I think you have a great opportunity for a white bar gap to emerge from contrasti ng space. I made some examples. 
- [x]  1's ear is too narrow
- [x]  3's mid terminal is too short, needs to extend left more
- [x]  5's bowl counter is too small, needs to be taller and the upper open counter made shorter
  - [x]  6's bowl counter is too small and low down too. I think you are matching the 8, but its not quite right. 
    7 is too narrow
- [x]  9'd tail kicks up too much at the end, should be flatter; also like the 6 its counter bowl is too small and high up. 
- [x]  Caps punctuation via OTL would be nice
- [x]  ?'s bowl is too small, make the vertical stem shorter to expand it; but the whole design is not matching the rest of the type so I would start from looking at the 9. 
- [x]  @'s got a flat segment in the inside of the out stroke of the a, make it smooth
- [x]  C's a bit strange. I wonder about flipping the cut angle, and made a c.alt
- [x]  K's fold is too high, and because of optical alignment, you can make the inside corner closer to the stem without a problem. I made a k.alt
- [x]  M's flat topped sharp points, like the A V W, are interesting, but could be bigger or replaced with real sharp points like you have in the Y. I like it! The diagonal left white bar is a nice off-key note. 
- [x]  N is too narrow
- [x]  Q's tail is too far around, it should shift a bit clockwise and down. I made Q.alt
- [x]  R's leg is too flat.
- [x]  S's bottom right needs work, especially the counter. The terminals are also at 15' not 30 which is weird.
- [x]  X's too narrow, and there is an optical compensation trick for diagonally crossing strokes which isn't used here, I think Thomas Phinney has a YouTube video about this. 
- [x]  Z's too narrow, and the top and bottom bars can be optically compensated, look at say Frutiger's Avenir's Z, the bottom right terminal is a little wider than the top, and left is twice as much farther to the left. 
- [x]  k's fold is not as high as K, but still a bit too high and too far right. 
- [x]  ]m and n have a weird bowl height difference. I wonder they should not have a shoulder, like the u. 
  - [x]  The 30' terminal in the a and e is weird, especially when the f g j are 90'
  - [x]  The 15' in the s works nicely. Here the smoothness is not right on the top, on the inside edge, between 7 and 8 o'clock
  - [x]  t's foot's outer edge has a big break in the curve, and is way too mechanical, it needs a little overshoot and a much higher start to the curve. Also like some letters that are thin, there doesn't need to be a white bar, so I removed it here. I made a t.alt
  - [x]  x's width is actually ok.
  - [x]  The { } and [ ] are too narrow, 
  - [x]  £ is too heavy in weight and like the ? needs to be redone as its too mechanical. 
  - [x]  There are a bunch of glyphs in the OTF that are unencoded and duplicate of encoded glyphs.

**Comment by megbaber** [comment]
i couldn't agree more with all of the above, well done Kosalaya and Pathum, we're really looking forward to seeing the final cut on Weds! x
