### ISSUE TITLE
Feature fix

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#56]
@paarandika @kosalaya 

<img width="318" alt="screen shot 2015-10-24 at 2 23 18 pm" src="https://cloud.githubusercontent.com/assets/6846609/10710674/e9a3991c-7a5b-11e5-82be-6bda32ef7c1a.png">

<img width="343" alt="screen shot 2015-10-24 at 2 27 30 pm" src="https://cloud.githubusercontent.com/assets/6846609/10710676/ef643352-7a5b-11e5-84f1-52701b61cd28.png">

<img width="354" alt="screen shot 2015-10-24 at 2 28 10 pm" src="https://cloud.githubusercontent.com/assets/6846609/10710679/f604af98-7a5b-11e5-9759-cc84c30c11d5.png">

<img width="195" alt="screen shot 2015-10-24 at 2 34 48 pm" src="https://cloud.githubusercontent.com/assets/6846609/10710694/7ac03662-7a5c-11e5-9820-ac75b411a61a.png">

**Comment by pathumego** [comment]
<img width="343" alt="screen shot 2015-10-24 at 2 27 30 pm" src="https://cloud.githubusercontent.com/assets/6846609/10710653/690d36a0-7a5b-11e5-8928-786192cb59f0.png">

**Comment by pathumego** [comment]
@paarandika

**Comment by paarandika** [comment]
Post the text here please

**Comment by pathumego** [comment]
what text?

**Comment by paarandika** [comment]
Original text in text form. Need to examine it.

**Comment by pathumego** [comment]
its all here http://mooniak.com/stick-no-bills-font/tests/

**Comment by paarandika** [comment]
නිරුපද්‍රිත is not typed correctly.
![ni](https://cloud.githubusercontent.com/assets/6725097/10737787/2430bddc-7c3a-11e5-9cb5-488742398cbd.PNG)
The problem with pillam is spacing error. It has nothing to do with features. @kosalaya it's your domain :)
![pillam](https://cloud.githubusercontent.com/assets/6725097/10737854/901afd5a-7c3a-11e5-86b1-3762e51c3cab.PNG)

**Comment by pathumego** [comment]
ok, is the rest fixed now?

**Comment by pathumego** [comment]
<img width="274" alt="screen shot 2015-10-26 at 7 54 17 pm" src="https://cloud.githubusercontent.com/assets/6846609/10740673/5ee551a0-7c1b-11e5-980e-32623d103cf1.png">

I still see the yansa error

**Comment by kosalaya** [comment]
this error is fixed now. but it's better if we can add an encoding slot for the letter ්‍යී

**Comment by pathumego** [comment]
You mean separate glyphs?

**Comment by kosalaya** [comment]
just for the Yansaya with MatraI and MatraIi.

**Comment by pathumego** [comment]
OK I filed #63. Closing this :+1:
