### ISSUE TITLE
u221A probem

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#60]
<img width="134" alt="screen shot 2015-10-25 at 2 08 41 am" src="https://cloud.githubusercontent.com/assets/6846609/10713712/69e7b5e8-7abd-11e5-9b52-d6d4a9172b47.png">

**Comment by kosalaya** [comment]
I​ changed this one. it doesn't come out well. the entire shape gets unrecognizable when it's matched with the width of the rest.

**Comment by pathumego** [comment]
@kosalaya Image please?

**Comment by pathumego** [comment]
Whats the status on this?

**Comment by kosalaya** [comment]
check the latest. i did some adjustments to it.

**Comment by pathumego** [comment]
Can you post a jpeg here please

**Comment by kosalaya** [comment]
<img width="509" alt="screen shot 2015-10-28 at 11 51 57 pm" src="https://cloud.githubusercontent.com/assets/8073976/10798701/f645a734-7dce-11e5-8dd2-c3dd6d0f186a.png">

**Comment by kosalaya** [comment]
what do you think?

**Comment by pathumego** [comment]
more weight?

**Comment by kosalaya** [comment]
now?
<img width="437" alt="screen shot 2015-10-29 at 12 12 22 am" src="https://cloud.githubusercontent.com/assets/8073976/10799236/cb36c322-7dd1-11e5-816f-95451194d0d2.png">
