### ISSUE TITLE
Fix Kundaliya :)

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#67]
Kundaliya feels like not balanced on right.

<img width="608" alt="screen shot 2015-11-05 at 5 06 42 pm" src="https://cloud.githubusercontent.com/assets/6846609/10975665/f02a47b2-83df-11e5-9df3-e121098b7d52.png">

A flat end to right side stroke would fix it.
<img width="660" alt="screen shot 2015-11-05 at 5 04 18 pm" src="https://cloud.githubusercontent.com/assets/6846609/10975668/f5b29b12-83df-11e5-966f-ad7ff679ff91.png">

**Comment by kosalaya** [comment]
<img width="533" alt="screen shot 2015-11-09 at 12 14 15 am" src="https://cloud.githubusercontent.com/assets/8073976/11021916/f6650ede-8676-11e5-93d8-d229b373b875.png">

**Comment by kosalaya** [comment]
are we good to go?

**Comment by pathumego** [comment]
:+1:
