### ISSUE TITLE
Tamil Interpolation errors

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#79]
@enathu @paarandika 

I checked the final built files. Did you see them? There are still a few glyphs failing interpolation.
If you open the final file in FF you can see the empty slots.

I did a test with Prepolator. Here are the glyphs that need fixing.

<img width="289" alt="screen shot 2015-12-21 at 12 15 56 pm" src="https://cloud.githubusercontent.com/assets/6846609/11930585/ab0abb6e-a7dc-11e5-8e1f-52e8cb2e7ead.png">

**Comment by pathumego** [comment]
@enathu Even after 72a36dd im seeing interpolation errors in some of the followin glyphs
<img width="144" alt="screen shot 2015-12-22 at 12 34 05 am" src="https://cloud.githubusercontent.com/assets/6846609/11945081/bce9f9f0-a843-11e5-85ce-35547a8b8395.png">

**Comment by enathu** [comment]
@pathumego Thank you Pathum. I'll have a look on to these and fix it. Cheers.

**Comment by pathumego** [comment]
@enathu Ping :)

**Comment by pathumego** [comment]
@enathu He I noticeed there are still some minor errors in interpolation. I will fix them using prepolator.

**Comment by pathumego** [comment]
@enathu tml_Rupee, month, Number is not compatible in point structure. And prepolator is still showing me errors with some other glyphs too.
<img width="105" alt="screen shot 2015-12-31 at 8 27 16 am" src="https://cloud.githubusercontent.com/assets/6846609/12062753/4a35b01c-af9a-11e5-85e6-d0b2618c9d57.png">

**Comment by pathumego** [comment]
ok so I did a a test. out of list, 

`Om Zero Rupee, month, Number, is not compatible point structure, you will have to redraw. 
<img width="849" alt="screen shot 2015-12-31 at 8 56 59 am" src="https://cloud.githubusercontent.com/assets/6846609/12062884/7b27062e-af9c-11e5-8d56-5482cf27b6b7.png">

Other glyphs have just contour order problems. I can fix them easily with Prepolator once you fix the redsign issues.

**Comment by enathu** [comment]
@pathumego Pathum, I am working on fixes for those point structure incompatible in Om, Zero, Rupee, month, Number signs. Will update the repo with the latest soon. Cheers.

**Comment by enathu** [comment]
@pathumego pushed a PR (https://github.com/mooniak/stick-no-bills-font/pull/83) with the fixes. Cheers.

**Comment by pathumego** [comment]
@kosalaya please fix these.
<img width="1180" alt="screen shot 2016-01-14 at 5 25 01 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331967/f568a260-bae3-11e5-94dd-73c5d4d91c28.png">
<img width="387" alt="screen shot 2016-01-14 at 5 24 46 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331969/f569f034-bae3-11e5-8bec-cc510a852351.png">
<img width="1164" alt="screen shot 2016-01-14 at 5 24 24 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331972/f56d7d12-bae3-11e5-85f1-4131a7bc2718.png">
<img width="1920" alt="screen shot 2016-01-14 at 5 24 20 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331968/f569ef94-bae3-11e5-93ed-87cadbcc1b6b.png">
<img width="781" alt="screen shot 2016-01-14 at 5 23 48 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331971/f56d738a-bae3-11e5-9bbb-da9f74d0ee19.png">
<img width="532" alt="screen shot 2016-01-14 at 5 23 30 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331970/f56ce7c6-bae3-11e5-88aa-f9d72850f18d.png">
<img width="848" alt="screen shot 2016-01-14 at 5 18 25 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331973/f58420bc-bae3-11e5-8971-8f50f21f5ca6.png">
<img width="1140" alt="screen shot 2016-01-14 at 5 18 16 pm" src="https://cloud.githubusercontent.com/assets/6846609/12331974/f588608c-bae3-11e5-9d07-a8ea4f662c9e.png">

**Comment by enathu** [comment]
@kosalaya Also, the LllIi has wrong contour order, please have a look and fix. Since the LllI, and LllIi are  originated as compound glyphs, by fixing the Llla will fix both glyphs' issue. Cheers.

![llla](https://cloud.githubusercontent.com/assets/62147/12353097/afa24d3e-bbb1-11e5-8bbe-9c9a53070d43.PNG)
![llli](https://cloud.githubusercontent.com/assets/62147/12353098/afe28750-bbb1-11e5-8ab4-56aa4c0edd9f.PNG)
![lllii](https://cloud.githubusercontent.com/assets/62147/12353099/afe79150-bbb1-11e5-9e7f-d4704b7a958f.PNG)

**Comment by pathumego** [comment]
@kosalaya can you fix these asap? then @paarandika can do rc for testing before final 1.2

**Comment by pathumego** [comment]
@enathu I found  issus caused by extra points such as this. 
<img width="711" alt="screen shot 2016-01-19 at 6 59 38 pm" src="https://cloud.githubusercontent.com/assets/6846609/12428862/0575c206-bedf-11e5-880e-343756d759d0.png">
