### ISSUE TITLE
Sinhala design improvement

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#80]
<img width="276" alt="screen shot 2015-12-21 at 3 53 08 pm" src="https://cloud.githubusercontent.com/assets/6846609/11934592/2331e914-a7fb-11e5-9428-32c7f58d98fb.png">

Relpace base+I matra of the following with the above 

<img width="282" alt="screen shot 2015-12-21 at 3 52 43 pm" src="https://cloud.githubusercontent.com/assets/6846609/11934593/2342750e-a7fb-11e5-92de-724d381ac0be.png">

**Comment by paarandika** [comment]
This can be corrected with features. I'll look in to that.

**Comment by paarandika** [comment]
![ndja](https://cloud.githubusercontent.com/assets/6725097/11938309/144c81b2-a840-11e5-8138-f350e4641ccf.PNG)
There is already a separate glyph for rakaransaya version. Two things are possible:
1. Create separate glyphs
2. Ignore existing rakaransaya glyph and use correct matra I versions with rakaransaya glyph
Hidden third option:
3. Use anchors for rakaransaya...

**Comment by pathumego** [comment]
using anchors is the best solution. But I think it should be adressed in the next release as a overall optimisation. We will start with SNB and then move onto Abhaya in Q1 2016

**Comment by pathumego** [comment]
@kosalaya @paarandika whats the status of this?
