### ISSUE TITLE
Om new design

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#91]
@enathu Can you work on this today? Ive fixed everything else, this is the only thing thats left :)

The intemediate weights look rellay bad with  the current desing
<img width="576" alt="screen shot 2016-01-20 at 1 16 30 pm" src="https://cloud.githubusercontent.com/assets/6846609/12449885/23c3e4e2-bf78-11e5-9aea-e1bbdd7a25cb.png">

I suggest something like this?

<img width="564" alt="screen shot 2016-01-20 at 1 15 38 pm" src="https://cloud.githubusercontent.com/assets/6846609/12449847/f48c6410-bf77-11e5-8ee4-da38e0aa4361.png">

In Balloo thambi this was done.

<img width="711" alt="screen shot 2016-01-20 at 1 18 19 pm" src="https://cloud.githubusercontent.com/assets/6846609/12449918/5679e5da-bf78-11e5-83f9-297d8ad54e44.png">

**Comment by pathumego** [comment]
@enathu Updates?

**Comment by enathu** [comment]
Pushed a PR, please merge.

**Comment by enathu** [comment]
The new OM for the reference.
![om](https://cloud.githubusercontent.com/assets/62147/12510627/54be73d6-c131-11e5-8377-2457bf1e5975.PNG)

**Comment by pathumego** [comment]
I did a bit of sdjustment to the bottom part. Thanks!
<img width="797" alt="screen shot 2016-01-22 at 1 36 38 pm" src="https://cloud.githubusercontent.com/assets/6846609/12511962/30e7c58a-c10d-11e5-8cff-67588b818e22.png">
