### ISSUE TITLE
Missing Glyphs in Tamil - Latest build

### ISSUE THREAD

**Issue by enathu** [mooniak/stick-no-bills-font#92]
Latest rc3 - v1.199 Pre Release hasn't got lots of glyphs in Tamil. Most of the missing glyphs are the compound glyphs of Tamil Vowel I. All the glyphs were present in the earlier version with the commit https://github.com/mooniak/stick-no-bills-font/commit/974430d9327d634240bae653be9dd7f96717c818

I suspect that the Tamil Vowel Sign I glyph isn't present in the latest build, which may cause this issue, please have a look. Cheers.

**Comment by pathumego** [comment]
ok i see these glyps with matraI, can you tell me whats missing?
<img width="1496" alt="screen shot 2016-01-21 at 8 43 55 am" src="https://cloud.githubusercontent.com/assets/6846609/12475485/3610f678-c01b-11e5-8167-d647ab2b1a95.png">

**Comment by enathu** [comment]
All the Matra I glyphs are present in the both source files, but they are missing in the build files in rc3 - v1.199 Pre Release! To name a few, tml_KI, tml_CI, tml_NyI, tml_TI, tml_NI, tml_MI and so on. Please have a look. If you go and look at the Specimen Page, you can see the missing glyphs.

![test1](https://cloud.githubusercontent.com/assets/62147/12483965/cccdf27a-c07d-11e5-835a-4e2c5e30243d.PNG)
_With latest build_
![test2](https://cloud.githubusercontent.com/assets/62147/12483966/ccd34d74-c07d-11e5-93de-bf0429420f4d.PNG)
_Earlier version_

Cheers.

**Comment by pathumego** [comment]
@enathu Ok thanks! Ill look at this.

**Comment by pathumego** [comment]
This is fixed
