### ISSUE TITLE
Translate description to Tamil

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#95]
@enathu Will you be able to write a few lines based on Description on README.md to go as a description?

**Comment by enathu** [comment]
@pathumego I'll push an update with Tamil text, tonight. Cheers.

**Comment by enathu** [comment]
Done. https://github.com/mooniak/stick-no-bills-font/pull/98

**Comment by pathumego** [comment]
@enathu Thanks!!!
