### ISSUE TITLE
Metadata improvments

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#97]
Build system handles metadata rather poorley. A fix to welipilla covering different tables is needed.

<img width="995" alt="screen shot 2016-01-23 at 12 18 48 pm" src="https://cloud.githubusercontent.com/assets/6846609/12530122/a70eb980-c1cb-11e5-86b9-33d345460abe.png">

**Comment by paarandika** [comment]
Can you list the tables that needs altering?

**Comment by pathumego** [comment]
Designer URL? THe thing is have to sit down and see what are all these tables and their metadata and labels. DIfferent platforms handle them differently. So i think it will be next step.

Anyway for TruFont this will have to figure out a way to intergrate different metadata sets and their relationship at one point. We can use that.

**Comment by pathumego** [comment]
We need a new build, so closing this. #105
